drop table DW_DIMENSION CASCADE;
drop table DW_LEVEL CASCADE;
drop table DW_LEVEL_DIRECT_ROLLUP CASCADE;
drop table DW_ATTRIBUTE CASCADE;
drop table DW_SIMPLE_BASE_MEASURE CASCADE;
drop table DW_DERIVED_BASE_MEASURE CASCADE;
drop table DW_DERIVED_BASE_MEASURE_USAGE CASCADE;
drop table DW_SIMPLE_AGGREGATE_MEASURE CASCADE;
drop table DW_DERIVED_AGGREGATE_MEASURE CASCADE;
drop table DW_DERIVED_AGGREGATE_MEASURE_USAGE CASCADE;
drop table DW_CUBE CASCADE;
drop table DW_CUBE_DIMENSION CASCADE;
drop table DW_CUBE_SIMPLE_BASE_MEASURE CASCADE;
drop table DW_CUBE_DERIVED_BASE_MEASURE CASCADE;
drop table DW_CUBE_DERIVED_AGGREGATE_MEASURE CASCADE;
drop table DW_DIM_OPERATOR CASCADE;
drop table DW_DIM_PREDICATE CASCADE;
drop table DW_DIM_PREDICATE_SUBSUMPTION CASCADE;
drop table DW_BMSR_PREDICATE CASCADE;
drop table DW_BMSR_PREDICATE_SUBSUMPTION CASCADE;
drop table DW_AMSR_PREDICATE CASCADE;
drop table DW_AMSR_PREDICATE_SUBSUMPTION CASCADE;
drop table DW_SCORE CASCADE;
drop table DW_SCORE_PREDICATE CASCADE;
drop table DW_SCORE_PREDICATE_SUBSUMPTION CASCADE;
drop table AGS_ANALYSIS_GRAPH_SCHEMA CASCADE;
drop table AGS_ANALYSIS_SITUATION_SCHEMA CASCADE;
drop table AGS_NON_CMP_ASS CASCADE;
drop table AGS_CMP_ASS CASCADE;
drop table AGS_COMPOSITE_ASS CASCADE;
drop table AGS_NASS_DIM_QUAL CASCADE;
drop table AGS_NASS_DIM_QUAL_SLICE_COND CASCADE;
drop table AGS_NASS_BMSR_FILTER CASCADE;
drop table AGS_NASS_AGGREGATE_MEASSURE CASCADE;
drop table AGS_NASS_AMSR_FILTER CASCADE;
drop table AGS_CASS_JOIN_COND CASCADE;
drop table AGS_CASS_SCORE CASCADE;
drop table AGS_CASS_SCORE_FILTER CASCADE;
drop table AGS_COMPOSITE_ASS_PART CASCADE;
drop table AGS_NAVSTEP_SCHEMA CASCADE;
drop table AGS_NAVSS_DRILL_DOWN_ONE_LEVEL CASCADE;
drop table AGS_NAVSS_DRILL_DOWN_TO_LEVEL CASCADE;
drop table AGS_NAVSS_ROLL_UP_ONE_LEVEL CASCADE;
drop table AGS_NAVSS_ROLL_UP_TO_LEVEL CASCADE;
drop table AGS_NAVSS_MOVE_DOWN_TO_NODE CASCADE;
drop table AGS_NAVSS_MOVE_UP_TO_NODE CASCADE;
drop table AGS_NAVSS_MOVE_ASIDE_TO_NODE CASCADE;
drop table AGS_NAVSS_MOVE_TO_NODE CASCADE;
drop table AGS_NAVSS_MOVE_TO_FIRST_NODE CASCADE;
drop table AGS_NAVSS_MOVE_TO_LAST_NODE CASCADE;
drop table AGS_NAVSS_MOVE_TO_NEXT_NODE CASCADE;
drop table AGS_NAVSS_MOVE_TO_PREV_NODE CASCADE;
drop table AGS_NAVSS_NARROW_SLICE_COND_A CASCADE;
drop table AGS_NAVSS_NARROW_SLICE_COND_A_PARS CASCADE;
drop table AGS_NAVSS_NARROW_SLICE_COND_C CASCADE;
drop table AGS_NAVSS_NARROW_SLICE_COND_C_PARS CASCADE;
drop table AGS_NAVSS_BROADEN_SLICE_COND_A CASCADE;
drop table AGS_NAVSS_BROADEN_SLICE_COND_A_PARS CASCADE;
drop table AGS_NAVSS_BROADEN_SLICE_COND_C CASCADE;
drop table AGS_NAVSS_BROADEN_SLICE_COND_C_PARS CASCADE;
drop table AGS_NAVSS_REFOCUS_SLICE_COND CASCADE;
drop table AGS_NAVSS_REFOCUS_SLICE_COND_PARS CASCADE;
drop table AGS_NAVSS_REFOCUS_SLICE_COND_C CASCADE;
drop table AGS_NAVSS_REFOCUS_SLICE_COND_C_PARS CASCADE;
drop table AGS_NAVSS_NARROW_BMSR_COND_A_PARS CASCADE;
drop table AGS_NAVSS_NARROW_BMSR_COND_C_PARS CASCADE;
drop table AGS_NAVSS_BROADEN_BMSR_COND_A_PARS CASCADE;
drop table AGS_NAVSS_BROADEN_BMSR_COND_C_PARS CASCADE;
drop table AGS_NAVSS_REFOCUS_BMSR_COND_PARS CASCADE;
drop table AGS_NAVSS_REFOCUS_BMSR_COND_C_PARS CASCADE;
drop table AGS_NAVSS_ADD_MEASURE_PARS CASCADE;
drop table AGS_NAVSS_DROP_MEASURE_PARS CASCADE;
drop table AGS_NAVSS_REFOCUS_MEASURE_PARS CASCADE;
drop table AGS_NAVSS_REFOCUS_MEASURE_C_PARS CASCADE;
drop table AGS_NAVSS_MOVE_DOWN_TO_MEASURE_PARS CASCADE;
drop table AGS_NAVSS_MOVE_UP_TO_MEASURE_PARS CASCADE;
drop table AGS_NAVSS_NARROW_AMSR_FILTER_A_PARS CASCADE;
drop table AGS_NAVSS_NARROW_AMSR_FILTER_C_PARS CASCADE;
drop table AGS_NAVSS_BROADEN_AMSR_FILTER_A_PARS CASCADE;
drop table AGS_NAVSS_BROADEN_AMSR_FILTER_C_PARS CASCADE;
drop table AGS_NAVSS_REFOCUS_AMSR_FILTER_PARS CASCADE;
drop table AGS_NAVSS_REFOCUS_AMSR_FILTER_C_PARS CASCADE;
drop table AGS_NAVSS_DRILL_ACROSS_TO_CUBE CASCADE;
drop table AGS_NAVSS_DRILL_ACROSS_TO_CUBE_BMSR_PRED CASCADE;
drop table AGS_NAVSS_DRILL_ACROSS_TO_CUBE_DAMSR CASCADE;
drop table AGS_NAVSS_DRILL_ACROSS_TO_CUBE_AMSR_PRED CASCADE;
drop table AGS_NAVSS_RELATE CASCADE;
drop table AGS_NAVSS_RELATE_JOIN CASCADE;
drop table AGS_NAVSS_RELATE_SCORE CASCADE;
drop table AGS_NAVSS_RELATE_SCORE_FLT CASCADE;
drop table AGS_NAVSS_TARGET CASCADE;
drop table AGS_NAVSS_TARGET_JOIN CASCADE;
drop table AGS_NAVSS_TARGET_SCORE CASCADE;
drop table AGS_NAVSS_TARGET_SCORE_FLT CASCADE;
drop table AGS_NAVSS_RERELATE CASCADE;
drop table AGS_NAVSS_RERELATE_JOIN CASCADE;
drop table AGS_NAVSS_RERELATE_SCORE CASCADE;
drop table AGS_NAVSS_RERELATE_SCORE_FLT CASCADE;
drop table AGS_NAVSS_RETARGET CASCADE;
drop table AGS_NAVSS_RETARGET_JOIN CASCADE;
drop table AGS_NAVSS_RETARGET_SCORE CASCADE;
drop table AGS_NAVSS_RETARGET_SCORE_FLT CASCADE;
drop table AGS_NAVSS_CORRELATE CASCADE;
drop table AGS_NAVSS_CORRELATE_JOIN CASCADE;
drop table AGS_NAVSS_CORRELATE_SCORE CASCADE;
drop table AGS_NAVSS_CORRELATE_SCORE_FLT CASCADE;
drop table AGS_NAVSS_NARROW_SCORE_FILTER_A_PARS CASCADE;
drop table AGS_NAVSS_NARROW_SCORE_FILTER_C_PARS CASCADE;
drop table AGS_NAVSS_BROADEN_SCORE_FILTER_A_PARS CASCADE;
drop table AGS_NAVSS_BROADEN_SCORE_FILTER_C_PARS CASCADE;
drop table AGS_NAVSS_REFOCUS_SCORE_FILTER_PARS CASCADE;
drop table AGS_NAVSS_REFOCUS_SCORE_FILTER_C_PARS CASCADE;
drop table AGS_NAVSS_REJOIN_JOIN CASCADE;
drop table AGS_NAVSS_REJOIN_SCORE CASCADE;
drop table AGS_NAVSS_REJOIN_SCORE_FLT CASCADE;
drop table AG_ANALYSIS_GRAPH CASCADE;
drop table AG_ANALYSIS_SITUATION CASCADE;
drop table AG_NON_CMP_AS CASCADE;
drop table AG_CMP_AS CASCADE;
drop table AG_COMPOSITE_AS CASCADE;
drop table AG_NAS_DIM_QUAL CASCADE;
drop table AG_NAS_DIM_QUAL_SLICE_COND CASCADE;
drop table AG_NAS_BMSR_FILTER CASCADE;
drop table AG_NAS_AGGREGATE_MEASURE CASCADE;
drop table AG_NAS_AMSR_FILTER CASCADE;
drop table AG_CAS_JOIN_COND CASCADE;
drop table AG_CAS_SCORE CASCADE;
drop table AG_CAS_SCORE_FILTER CASCADE;
drop table AG_COMPOSITE_AS_PART CASCADE;
drop table AG_NAVSTEP CASCADE;
drop table AG_NAVS_DRILL_DOWN_ONE_LEVEL CASCADE;
drop table AG_NAVS_DRILL_DOWN_TO_LEVEL CASCADE;
drop table AG_NAVS_ROLL_UP_ONE_LEVEL CASCADE;
drop table AG_NAVS_ROLL_UP_TO_LEVEL CASCADE;
drop table AG_NAVS_MOVE_DOWN_TO_NODE CASCADE;
drop table AG_NAVS_MOVE_UP_TO_NODE CASCADE;
drop table AG_NAVS_MOVE_ASIDE_TO_NODE CASCADE;
drop table AG_NAVS_MOVE_TO_NODE CASCADE;
drop table AG_NAVS_MOVE_TO_FIRST_NODE CASCADE;
drop table AG_NAVS_MOVE_TO_LAST_NODE CASCADE;
drop table AG_NAVS_MOVE_TO_NEXT_NODE CASCADE;
drop table AG_NAVS_MOVE_TO_PREV_NODE CASCADE;
drop table AG_NAVS_NARROW_SLICE_COND_A CASCADE;
drop table AG_NAVS_NARROW_SLICE_COND_A_PARS CASCADE;
drop table AG_NAVS_NARROW_SLICE_COND_C CASCADE;
drop table AG_NAVS_NARROW_SLICE_COND_C_PARS CASCADE;
drop table AG_NAVS_BROADEN_SLICE_COND_A CASCADE;
drop table AG_NAVS_BROADEN_SLICE_COND_A_PARS CASCADE;
drop table AG_NAVS_BROADEN_SLICE_COND_C CASCADE;
drop table AG_NAVS_BROADEN_SLICE_COND_C_PARS CASCADE;
drop table AG_NAVS_REFOCUS_SLICE_COND CASCADE;
drop table AG_NAVS_REFOCUS_SLICE_COND_PARS CASCADE;
drop table AG_NAVS_REFOCUS_SLICE_COND_C CASCADE;
drop table AG_NAVS_REFOCUS_SLICE_COND_C_PARS CASCADE;
drop table AG_NAVS_NARROW_BMSR_COND_A_PARS CASCADE;
drop table AG_NAVS_NARROW_BMSR_COND_C_PARS CASCADE;
drop table AG_NAVS_BROADEN_BMSR_COND_A_PARS CASCADE;
drop table AG_NAVS_BROADEN_BMSR_COND_C_PARS CASCADE;
drop table AG_NAVS_REFOCUS_BMSR_COND_PARS CASCADE;
drop table AG_NAVS_REFOCUS_BMSR_COND_C_PARS CASCADE;
drop table AG_NAVS_ADD_MEASURE_PARS CASCADE;
drop table AG_NAVS_DROP_MEASURE_PARS CASCADE;
drop table AG_NAVS_REFOCUS_MEASURE_PARS CASCADE;
drop table AG_NAVS_REFOCUS_MEASURE_C_PARS CASCADE;
drop table AG_NAVS_MOVE_DOWN_TO_MEASURE_PARS CASCADE;
drop table AG_NAVS_MOVE_UP_TO_MEASURE_PARS CASCADE;
drop table AG_NAVS_NARROW_AMSR_FILTER_A_PARS CASCADE;
drop table AG_NAVS_NARROW_AMSR_FILTER_C_PARS CASCADE;
drop table AG_NAVS_BROADEN_AMSR_FILTER_A_PARS CASCADE;
drop table AG_NAVS_BROADEN_AMSR_FILTER_C_PARS CASCADE;
drop table AG_NAVS_REFOCUS_AMSR_FILTER_PARS CASCADE;
drop table AG_NAVS_REFOCUS_AMSR_FILTER_C_PARS CASCADE;
drop table AG_NAVS_DRILL_ACROSS_TO_CUBE CASCADE;
drop table AG_NAVS_DRILL_ACROSS_TO_CUBE_BMSR_PRED CASCADE;
drop table AG_NAVS_DRILL_ACROSS_TO_CUBE_DAMSR CASCADE;
drop table AG_NAVS_DRILL_ACROSS_TO_CUBE_AMSR_PRED CASCADE;
drop table AG_NAVS_RELATE CASCADE;
drop table AG_NAVS_RELATE_JOIN CASCADE;
drop table AG_NAVS_RELATE_SCORE CASCADE;
drop table AG_NAVS_RELATE_SCORE_FLT CASCADE;
drop table AG_NAVS_TARGET CASCADE;
drop table AG_NAVS_TARGET_JOIN CASCADE;
drop table AG_NAVS_TARGET_SCORE CASCADE;
drop table AG_NAVS_TARGET_SCORE_FLT CASCADE;
drop table AG_NAVS_RERELATE CASCADE;
drop table AG_NAVS_RERELATE_JOIN CASCADE;
drop table AG_NAVS_RERELATE_SCORE CASCADE;
drop table AG_NAVS_RERELATE_SCORE_FLT CASCADE;
drop table AG_NAVS_RETARGET CASCADE;
drop table AG_NAVS_RETARGET_JOIN CASCADE;
drop table AG_NAVS_RETARGET_SCORE CASCADE;
drop table AG_NAVS_RETARGET_SCORE_FLT CASCADE;
drop table AG_NAVS_CORRELATE CASCADE;
drop table AG_NAVS_CORRELATE_JOIN CASCADE;
drop table AG_NAVS_CORRELATE_SCORE CASCADE;
drop table AG_NAVS_CORRELATE_SCORE_FLT CASCADE;
drop table AG_NAVS_NARROW_SCORE_FILTER_A_PARS CASCADE;
drop table AG_NAVS_NARROW_SCORE_FILTER_C_PARS CASCADE;
drop table AG_NAVS_BROADEN_SCORE_FILTER_A_PARS CASCADE;
drop table AG_NAVS_BROADEN_SCORE_FILTER_C_PARS CASCADE;
drop table AG_NAVS_REFOCUS_SCORE_FILTER_PARS CASCADE;
drop table AG_NAVS_REFOCUS_SCORE_FILTER_C_PARS CASCADE;
drop table AG_NAVS_REJOIN_JOIN CASCADE;
drop table AG_NAVS_REJOIN_SCORE CASCADE;
drop table AG_NAVS_REJOIN_SCORE_FLT CASCADE;



CREATE TABLE DW_DIMENSION (
	DIM_SID		int NOT NULL PRIMARY KEY,
	DIM_NAME	varchar(250) NOT NULL UNIQUE
);

CREATE TABLE DW_LEVEL (
	LVL_SID			int NOT NULL PRIMARY KEY,
	LVL_NAME		varchar(250) NOT NULL UNIQUE,
	DIM_SID			int NOT NULL,
	LVL_DATATYPE	varchar(20) NOT NULL,
	LVL_POSITION	smallint NOT NULL,
	
	FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE DW_LEVEL_DIRECT_ROLLUP (
	LVL_SID_SUB		int NOT NULL,
	LVL_SID_SUPER	int NOT NULL,

	PRIMARY KEY (LVL_SID_SUB, LVL_SID_SUPER),
	FOREIGN KEY (LVL_SID_SUB) REFERENCES DW_LEVEL(LVL_SID) ON DELETE CASCADE,
	FOREIGN KEY (LVL_SID_SUPER) REFERENCES DW_LEVEL(LVL_SID) ON DELETE CASCADE
);

CREATE TABLE DW_ATTRIBUTE (
	ATTR_SID		int NOT NULL PRIMARY KEY,
	ATTR_NAME		varchar(250) NOT NULL UNIQUE,
	LVL_SID			int NOT NULL,
	ATTR_DATATYPE	varchar(20) NOT NULL,
	
	FOREIGN KEY (LVL_SID) REFERENCES DW_LEVEL(LVL_SID) ON DELETE CASCADE
);

CREATE TABLE DW_SIMPLE_BASE_MEASURE (
	SBMSR_SID	int NOT NULL PRIMARY KEY,
	SBMSR_NAME	varchar(250) NOT NULL UNIQUE
);

CREATE TABLE DW_DERIVED_BASE_MEASURE (
	DBMSR_SID	int NOT NULL PRIMARY KEY,
	DBMSR_NAME	varchar(250) NOT NULL UNIQUE,
	DBMSR_EXPR	varchar(5000) NOT NULL,
	SBMSR_SID	int,
	ATTR_SID	int,
	
	FOREIGN KEY (SBMSR_SID) REFERENCES DW_SIMPLE_BASE_MEASURE(SBMSR_SID) ON DELETE CASCADE,
	FOREIGN KEY (ATTR_SID) REFERENCES DW_ATTRIBUTE(ATTR_SID) ON DELETE CASCADE
);

CREATE TABLE DW_DERIVED_BASE_MEASURE_USAGE (
	DBMSR_SID		int NOT NULL,
	DBMSR_SID_USED	int NOT NULL,

	PRIMARY KEY (DBMSR_SID, DBMSR_SID_USED),
	FOREIGN KEY (DBMSR_SID) REFERENCES DW_DERIVED_BASE_MEASURE(DBMSR_SID) ON DELETE CASCADE,
	FOREIGN KEY (DBMSR_SID_USED) REFERENCES DW_DERIVED_BASE_MEASURE(DBMSR_SID) ON DELETE CASCADE
);

CREATE TABLE DW_SIMPLE_AGGREGATE_MEASURE (
	SAMSR_SID	int NOT NULL PRIMARY KEY,
	SAMSR_NAME	varchar(250) NOT NULL UNIQUE,
	SAMSR_EXPR	varchar(5000) NOT NULL,
	DBMSR_SID	int,
	LVL_SID		int,
	
	FOREIGN KEY (DBMSR_SID) REFERENCES DW_DERIVED_BASE_MEASURE(DBMSR_SID) ON DELETE CASCADE,
	FOREIGN KEY (LVL_SID) REFERENCES DW_LEVEL(LVL_SID) ON DELETE CASCADE
);

CREATE TABLE DW_DERIVED_AGGREGATE_MEASURE (
	DAMSR_SID	int NOT NULL PRIMARY KEY,
	DAMSR_NAME	varchar(250) NOT NULL UNIQUE,
	DAMSR_EXPR	varchar(5000) NOT NULL,
	SAMSR_SID	int,
	
	FOREIGN KEY (SAMSR_SID) REFERENCES DW_SIMPLE_AGGREGATE_MEASURE(SAMSR_SID) ON DELETE CASCADE
);

CREATE TABLE DW_DERIVED_AGGREGATE_MEASURE_USAGE (
	DAMSR_SID		int NOT NULL,
	DAMSR_SID_USED	int NOT NULL,

	PRIMARY KEY (DAMSR_SID, DAMSR_SID_USED),
	FOREIGN KEY (DAMSR_SID) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE,
	FOREIGN KEY (DAMSR_SID_USED) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE
);

CREATE TABLE DW_CUBE (
	CUBE_SID	int NOT NULL PRIMARY KEY,
	CUBE_NAME	varchar(250) NOT NULL UNIQUE
);

CREATE TABLE DW_CUBE_DIMENSION (
	CUBE_SID	int NOT NULL,
	DIM_SID		int NOT NULL,

	PRIMARY KEY (CUBE_SID, DIM_SID),
	FOREIGN KEY (CUBE_SID) REFERENCES DW_CUBE(CUBE_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE DW_CUBE_SIMPLE_BASE_MEASURE (
	CUBE_SID	int NOT NULL,
	SBMSR_SID	int NOT NULL,

	PRIMARY KEY (CUBE_SID, SBMSR_SID),
	FOREIGN KEY (CUBE_SID) REFERENCES DW_CUBE(CUBE_SID) ON DELETE CASCADE,
	FOREIGN KEY (SBMSR_SID) REFERENCES DW_SIMPLE_BASE_MEASURE(SBMSR_SID) ON DELETE CASCADE
);

CREATE TABLE DW_CUBE_DERIVED_BASE_MEASURE (
	CUBE_SID	int NOT NULL,
	DBMSR_SID	int NOT NULL,

	PRIMARY KEY (CUBE_SID, DBMSR_SID),
	FOREIGN KEY (CUBE_SID) REFERENCES DW_CUBE(CUBE_SID) ON DELETE CASCADE,
	FOREIGN KEY (DBMSR_SID) REFERENCES DW_DERIVED_BASE_MEASURE(DBMSR_SID) ON DELETE CASCADE
);

CREATE TABLE DW_CUBE_DERIVED_AGGREGATE_MEASURE (
	CUBE_SID	int NOT NULL,
	DAMSR_SID	int NOT NULL,

	PRIMARY KEY (CUBE_SID, DAMSR_SID),
	FOREIGN KEY (CUBE_SID) REFERENCES DW_CUBE(CUBE_SID) ON DELETE CASCADE,
	FOREIGN KEY (DAMSR_SID) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE
);

CREATE TABLE DW_DIM_OPERATOR (
	DIM_OP_SID	int NOT NULL PRIMARY KEY,
	DIM_OP_NAME	varchar(250) NOT NULL UNIQUE,
	LVL_SID		int NOT NULL,
	DIM_OP_EXPR	varchar(5000) NOT NULL,
	
	FOREIGN KEY (LVL_SID) REFERENCES DW_LEVEL(LVL_SID) ON DELETE CASCADE
);

CREATE TABLE DW_DIM_PREDICATE (
	DIM_PRED_SID	int NOT NULL PRIMARY KEY,
	DIM_PRED_NAME	varchar(250) NOT NULL UNIQUE,
	LVL_SID			int NOT NULL,
	DIM_PRED_EXPR	varchar(5000) NOT NULL,
	
	FOREIGN KEY (LVL_SID) REFERENCES DW_LEVEL(LVL_SID) ON DELETE CASCADE
);

CREATE TABLE DW_DIM_PREDICATE_SUBSUMPTION (
	DIM_PRED_SID_SUBSUMER	int NOT NULL,
	DIM_PRED_SID_SUBSUMEE	int NOT NULL,

	PRIMARY KEY (DIM_PRED_SID_SUBSUMER, DIM_PRED_SID_SUBSUMEE),
	FOREIGN KEY (DIM_PRED_SID_SUBSUMER) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_PRED_SID_SUBSUMEE) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE DW_BMSR_PREDICATE (
	BMSR_PRED_SID	int NOT NULL PRIMARY KEY,
	BMSR_PRED_NAME	varchar(250) NOT NULL UNIQUE,
	CUBE_SID		int NOT NULL,
	BMSR_PRED_EXPR	varchar(5000) NOT NULL,
	
	FOREIGN KEY (CUBE_SID) REFERENCES DW_CUBE(CUBE_SID) ON DELETE CASCADE
);

CREATE TABLE DW_BMSR_PREDICATE_SUBSUMPTION (
	BMSR_PRED_SID_SUBSUMER	int NOT NULL,
	BMSR_PRED_SID_SUBSUMEE	int NOT NULL,

	PRIMARY KEY (BMSR_PRED_SID_SUBSUMER, BMSR_PRED_SID_SUBSUMEE),
	FOREIGN KEY (BMSR_PRED_SID_SUBSUMER) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE,
	FOREIGN KEY (BMSR_PRED_SID_SUBSUMEE) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE DW_AMSR_PREDICATE (
	AMSR_PRED_SID	int NOT NULL PRIMARY KEY,
	AMSR_PRED_NAME	varchar(250) NOT NULL UNIQUE,
	CUBE_SID		int NOT NULL,
	AMSR_PRED_EXPR	varchar(5000) NOT NULL,
	
	FOREIGN KEY (CUBE_SID) REFERENCES DW_CUBE(CUBE_SID) ON DELETE CASCADE
);

CREATE TABLE DW_AMSR_PREDICATE_SUBSUMPTION (
	AMSR_PRED_SID_SUBSUMER	int NOT NULL,
	AMSR_PRED_SID_SUBSUMEE	int NOT NULL,

	PRIMARY KEY (AMSR_PRED_SID_SUBSUMER, AMSR_PRED_SID_SUBSUMEE),
	FOREIGN KEY (AMSR_PRED_SID_SUBSUMER) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE,
	FOREIGN KEY (AMSR_PRED_SID_SUBSUMEE) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE DW_SCORE (
	SCORE_SID	int NOT NULL PRIMARY KEY,
	SCORE_NAME	varchar(250) NOT NULL UNIQUE,
	SCORE_EXPR	varchar(5000) NOT NULL
);

CREATE TABLE DW_SCORE_PREDICATE (
	SCORE_PRED_SID	int NOT NULL PRIMARY KEY,
	SCORE_PRED_NAME	varchar(250) NOT NULL UNIQUE,
	SCORE_PRED_EXPR	varchar(5000) NOT NULL
);

CREATE TABLE DW_SCORE_PREDICATE_SUBSUMPTION (
	SCORE_PRED_SID_SUBSUMER	int NOT NULL,
	SCORE_PRED_SID_SUBSUMEE	int NOT NULL,

	PRIMARY KEY (SCORE_PRED_SID_SUBSUMER, SCORE_PRED_SID_SUBSUMEE),
	FOREIGN KEY (SCORE_PRED_SID_SUBSUMER) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_PRED_SID_SUBSUMEE) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);


CREATE TABLE AGS_ANALYSIS_GRAPH_SCHEMA (
	AGS_SID			int NOT NULL PRIMARY KEY,
	AGS_NAME		varchar(250) NOT NULL UNIQUE,
	AGS_DESCRIPTION	varchar(5000)
);

CREATE TABLE AGS_ANALYSIS_SITUATION_SCHEMA (
	ASS_SID			int NOT NULL PRIMARY KEY,
	ASS_NAME		varchar(250) NOT NULL,
	ASS_DESCRIPTION	varchar(5000),
	AGS_SID			int NOT NULL,
	ASS_POS_X		int NOT NULL,
	ASS_POS_Y		int NOT NULL,
	
	FOREIGN KEY (AGS_SID) REFERENCES AGS_ANALYSIS_GRAPH_SCHEMA(AGS_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NON_CMP_ASS (
	ASS_SID_NASS		int NOT NULL PRIMARY KEY,
	ASS_USED_IN_CASS	smallint NOT NULL,
	CUBE_SID			int NOT NULL,
	
	FOREIGN KEY (ASS_SID_NASS) REFERENCES AGS_ANALYSIS_SITUATION_SCHEMA(ASS_SID) ON DELETE CASCADE,
	FOREIGN KEY (CUBE_SID) REFERENCES DW_CUBE(CUBE_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_CMP_ASS (
	ASS_SID_CASS		int NOT NULL PRIMARY KEY,
	ASS_SID_NASS_COI	int NOT NULL,
	ASS_SID_NASS_COC	int NOT NULL,
	
	FOREIGN KEY (ASS_SID_CASS) REFERENCES AGS_ANALYSIS_SITUATION_SCHEMA(ASS_SID) ON DELETE CASCADE,
	FOREIGN KEY (ASS_SID_NASS_COI) REFERENCES AGS_NON_CMP_ASS(ASS_SID_NASS) ON DELETE CASCADE,
	FOREIGN KEY (ASS_SID_NASS_COC) REFERENCES AGS_NON_CMP_ASS(ASS_SID_NASS) ON DELETE CASCADE
);

CREATE TABLE AGS_COMPOSITE_ASS (
	ASS_SID_COMPOSITE	int NOT NULL PRIMARY KEY,
	ASS_SID_ROOT		int NOT NULL,
	
	FOREIGN KEY (ASS_SID_COMPOSITE) REFERENCES AGS_ANALYSIS_SITUATION_SCHEMA(ASS_SID) ON DELETE CASCADE,
	FOREIGN KEY (ASS_SID_ROOT) REFERENCES AGS_ANALYSIS_SITUATION_SCHEMA(ASS_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NASS_DIM_QUAL (
	NASS_DQ_SID			int NOT NULL PRIMARY KEY,
	ASS_SID_NASS		int NOT NULL,
	DIM_SID				int NOT NULL,
	LVL_SID_DICELVL		int,
	NASS_DQ_DICE_NODE	varchar(5000),
	LVL_SID_GRANLVL		int,
	
	FOREIGN KEY (ASS_SID_NASS) REFERENCES AGS_NON_CMP_ASS(ASS_SID_NASS) ON DELETE CASCADE,
	FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE,
	FOREIGN KEY (LVL_SID_DICELVL) REFERENCES DW_LEVEL(LVL_SID) ON DELETE CASCADE,
	FOREIGN KEY (LVL_SID_GRANLVL) REFERENCES DW_LEVEL(LVL_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NASS_DIM_QUAL_SLICE_COND (
	NASS_SC_SID		int NOT NULL PRIMARY KEY,
	NASS_DQ_SID		int NOT NULL,
	DIM_PRED_SID	int NOT NULL,
	
	FOREIGN KEY (NASS_DQ_SID) REFERENCES AGS_NASS_DIM_QUAL(NASS_DQ_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_PRED_SID) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NASS_BMSR_FILTER (
	NASS_BMSR_FLT_SID	int NOT NULL PRIMARY KEY,
	ASS_SID_NASS		int NOT NULL,
	BMSR_PRED_SID		int NOT NULL,
	
	FOREIGN KEY (ASS_SID_NASS) REFERENCES AGS_NON_CMP_ASS(ASS_SID_NASS) ON DELETE CASCADE,
	FOREIGN KEY (BMSR_PRED_SID) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NASS_AGGREGATE_MEASSURE (
	NASS_AMSR_SID	int NOT NULL PRIMARY KEY,
	ASS_SID_NASS	int NOT NULL,
	DAMSR_SID		int NOT NULL,
	
	FOREIGN KEY (ASS_SID_NASS) REFERENCES AGS_NON_CMP_ASS(ASS_SID_NASS) ON DELETE CASCADE,
	FOREIGN KEY (DAMSR_SID) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NASS_AMSR_FILTER (
	NASS_AMSR_FLT_SID	int NOT NULL PRIMARY KEY,
	ASS_SID_NASS		int NOT NULL,
	AMSR_PRED_SID		int NOT NULL,
	
	FOREIGN KEY (ASS_SID_NASS) REFERENCES AGS_NON_CMP_ASS(ASS_SID_NASS) ON DELETE CASCADE,
	FOREIGN KEY (AMSR_PRED_SID) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_CASS_JOIN_COND (
	CASS_JOIN_SID	int NOT NULL PRIMARY KEY,
	ASS_SID_CASS	int NOT NULL,
	CASS_JOIN_EXPR	varchar(5000) NOT NULL,
	
	FOREIGN KEY (ASS_SID_CASS) REFERENCES AGS_CMP_ASS(ASS_SID_CASS) ON DELETE CASCADE
);

CREATE TABLE AGS_CASS_SCORE (
	CASS_SCORE_SID	int NOT NULL PRIMARY KEY,
	ASS_SID_CASS	int NOT NULL,
	SCORE_SID		int NOT NULL,
	
	FOREIGN KEY (ASS_SID_CASS) REFERENCES AGS_CMP_ASS(ASS_SID_CASS) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_SID) REFERENCES DW_SCORE(SCORE_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_CASS_SCORE_FILTER (
	CASS_SCORE_FLT_SID	int NOT NULL PRIMARY KEY,
	ASS_SID_CASS		int NOT NULL,
	SCORE_PRED_SID		int NOT NULL,
	
	FOREIGN KEY (ASS_SID_CASS) REFERENCES AGS_CMP_ASS(ASS_SID_CASS) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_PRED_SID) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_COMPOSITE_ASS_PART (
	ASS_SID_COMPOSITE	int NOT NULL,
	ASS_SID_PART		int NOT NULL,

	PRIMARY KEY (ASS_SID_COMPOSITE, ASS_SID_PART),
	FOREIGN KEY (ASS_SID_COMPOSITE) REFERENCES AGS_CMP_ASS(ASS_SID_CASS) ON DELETE CASCADE,
	FOREIGN KEY (ASS_SID_PART) REFERENCES AGS_ANALYSIS_SITUATION_SCHEMA(ASS_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSTEP_SCHEMA (
	NAVSS_SID				int NOT NULL PRIMARY KEY,
	AGS_SID					int NOT NULL,
	ASS_SID_SOURCE			int NOT NULL,
	ASS_SID_TARGET			int NOT NULL,
	NAVSS_OPNAME			varchar(250) NOT NULL,
	NAVSS_GRD_EXPR			varchar(5000),
	NAVSS_USED_IN_CMPNAV	smallint NOT NULL,
	NAVSS_POS_X				int NOT NULL,
	NAVSS_POS_Y				int NOT NULL,
	NAVSS_POS_GRD_X			int NOT NULL,
	NAVSS_POS_GRD_Y			int NOT NULL,
	
	FOREIGN KEY (AGS_SID) REFERENCES AGS_ANALYSIS_GRAPH_SCHEMA(AGS_SID) ON DELETE CASCADE,
	FOREIGN KEY (ASS_SID_SOURCE) REFERENCES AGS_ANALYSIS_SITUATION_SCHEMA(ASS_SID) ON DELETE CASCADE,
	FOREIGN KEY (ASS_SID_TARGET) REFERENCES AGS_ANALYSIS_SITUATION_SCHEMA(ASS_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_DRILL_DOWN_ONE_LEVEL (
	NAVSS_SID	int NOT NULL PRIMARY KEY,
	DIM_SID		int NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_DRILL_DOWN_TO_LEVEL (
	NAVSS_SID		int NOT NULL PRIMARY KEY,
	DIM_SID			int NOT NULL,
	LVL_SID_GRANLVL	int,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE,
	FOREIGN KEY (LVL_SID_GRANLVL) REFERENCES DW_LEVEL(LVL_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_ROLL_UP_ONE_LEVEL (
	NAVSS_SID	int NOT NULL PRIMARY KEY,
	DIM_SID		int NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_ROLL_UP_TO_LEVEL (
	NAVSS_SID		int NOT NULL PRIMARY KEY,
	DIM_SID			int NOT NULL,
	LVL_SID_GRANLVL	int,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE,
	FOREIGN KEY (LVL_SID_GRANLVL) REFERENCES DW_LEVEL(LVL_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_MOVE_DOWN_TO_NODE (
	NAVSS_SID		int NOT NULL PRIMARY KEY,
	DIM_SID			int NOT NULL,
	LVL_SID_DICELVL	int NOT NULL,
	NAVSS_DICE_NODE	varchar(5000) NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE,
	FOREIGN KEY (LVL_SID_DICELVL) REFERENCES DW_LEVEL(LVL_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_MOVE_UP_TO_NODE (
	NAVSS_SID		int NOT NULL PRIMARY KEY,
	DIM_SID			int NOT NULL,
	LVL_SID_DICELVL	int NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE,
	FOREIGN KEY (LVL_SID_DICELVL) REFERENCES DW_LEVEL(LVL_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_MOVE_ASIDE_TO_NODE (
	NAVSS_SID		int NOT NULL PRIMARY KEY,
	DIM_SID			int NOT NULL,
	NAVSS_DICE_NODE	varchar(5000) NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_MOVE_TO_NODE (
	NAVSS_SID		int NOT NULL PRIMARY KEY,
	DIM_SID			int NOT NULL,
	LVL_SID_DICELVL	int NOT NULL,
	NAVSS_DICE_NODE	varchar(5000) NOT NULL,
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE,
	FOREIGN KEY (LVL_SID_DICELVL) REFERENCES DW_LEVEL(LVL_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_MOVE_TO_FIRST_NODE (
	NAVSS_SID	int NOT NULL PRIMARY KEY,
	DIM_SID		int NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_MOVE_TO_LAST_NODE (
	NAVSS_SID	int NOT NULL PRIMARY KEY,
	DIM_SID		int NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_MOVE_TO_NEXT_NODE (
	NAVSS_SID	int NOT NULL PRIMARY KEY,
	DIM_SID		int NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_MOVE_TO_PREV_NODE (
	NAVSS_SID	int NOT NULL PRIMARY KEY,
	DIM_SID		int NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_NARROW_SLICE_COND_A (
	NAVSS_SID	int NOT NULL PRIMARY KEY,
	DIM_SID		int NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_NARROW_SLICE_COND_A_PARS (
	NAVSS_SID		int NOT NULL,
	DIM_PRED_SID	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, DIM_PRED_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_PRED_SID) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_NARROW_SLICE_COND_C (
	NAVSS_SID	int NOT NULL PRIMARY KEY,
	DIM_SID		int NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_NARROW_SLICE_COND_A(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_NARROW_SLICE_COND_C_PARS (
	NAVSS_SID			int NOT NULL,
	DIM_PRED_SID_OLD	int NOT NULL,
	DIM_PRED_SID_NEW	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, DIM_PRED_SID_OLD),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_NARROW_SLICE_COND_C(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_PRED_SID_OLD) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_PRED_SID_NEW) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_BROADEN_SLICE_COND_A (
	NAVSS_SID	int NOT NULL PRIMARY KEY,
	DIM_SID		int NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_BROADEN_SLICE_COND_A_PARS (
	NAVSS_SID		int NOT NULL,
	DIM_PRED_SID	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, DIM_PRED_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_BROADEN_SLICE_COND_A(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_PRED_SID) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_BROADEN_SLICE_COND_C (
	NAVSS_SID	int NOT NULL PRIMARY KEY,
	DIM_SID		int NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_BROADEN_SLICE_COND_C_PARS (
	NAVSS_SID			int NOT NULL,
	DIM_PRED_SID_OLD	int NOT NULL,
	DIM_PRED_SID_NEW	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, DIM_PRED_SID_OLD),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_BROADEN_SLICE_COND_C(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_PRED_SID_OLD) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_PRED_SID_NEW) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_REFOCUS_SLICE_COND (
	NAVSS_SID	int NOT NULL PRIMARY KEY,
	DIM_SID		int NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_REFOCUS_SLICE_COND_PARS (
	NAVSS_SID		int NOT NULL,
	DIM_PRED_SID	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, DIM_PRED_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_REFOCUS_SLICE_COND(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_PRED_SID) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_REFOCUS_SLICE_COND_C (
	NAVSS_SID	int NOT NULL PRIMARY KEY,
	DIM_SID		int NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_REFOCUS_SLICE_COND_C_PARS (
	NAVSS_SID			int NOT NULL,
	DIM_PRED_SID_OLD	int NOT NULL,
	DIM_PRED_SID_NEW	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, DIM_PRED_SID_OLD),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_REFOCUS_SLICE_COND_C(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_PRED_SID_OLD) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE,
	FOREIGN KEY (DIM_PRED_SID_NEW) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_NARROW_BMSR_COND_A_PARS (
	NAVSS_SID		int NOT NULL,
	BMSR_PRED_SID	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, BMSR_PRED_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (BMSR_PRED_SID) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_NARROW_BMSR_COND_C_PARS (
	NAVSS_SID			int NOT NULL,
	BMSR_PRED_SID_OLD	int NOT NULL,
	BMSR_PRED_SID_NEW	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, BMSR_PRED_SID_OLD),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (BMSR_PRED_SID_OLD) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE,
	FOREIGN KEY (BMSR_PRED_SID_NEW) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_BROADEN_BMSR_COND_A_PARS (
	NAVSS_SID		int NOT NULL,
	BMSR_PRED_SID	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, BMSR_PRED_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (BMSR_PRED_SID) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_BROADEN_BMSR_COND_C_PARS (
	NAVSS_SID			int NOT NULL,
	BMSR_PRED_SID_OLD	int NOT NULL,
	BMSR_PRED_SID_NEW	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, BMSR_PRED_SID_OLD),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (BMSR_PRED_SID_OLD) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE,
	FOREIGN KEY (BMSR_PRED_SID_NEW) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_REFOCUS_BMSR_COND_PARS (
	NAVSS_SID		int NOT NULL,
	BMSR_PRED_SID	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, BMSR_PRED_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (BMSR_PRED_SID) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_REFOCUS_BMSR_COND_C_PARS (
	NAVSS_SID			int NOT NULL,
	BMSR_PRED_SID_OLD	int NOT NULL,
	BMSR_PRED_SID_NEW	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, BMSR_PRED_SID_OLD),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (BMSR_PRED_SID_OLD) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE,
	FOREIGN KEY (BMSR_PRED_SID_NEW) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_ADD_MEASURE_PARS (
	NAVSS_SID	int NOT NULL,
	DAMSR_SID	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, DAMSR_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DAMSR_SID) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_DROP_MEASURE_PARS (
	NAVSS_SID	int NOT NULL,
	DAMSR_SID	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, DAMSR_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DAMSR_SID) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_REFOCUS_MEASURE_PARS (
	NAVSS_SID	int NOT NULL,
	DAMSR_SID	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, DAMSR_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DAMSR_SID) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_REFOCUS_MEASURE_C_PARS (
	NAVSS_SID		int NOT NULL,
	DAMSR_SID_OLD	int NOT NULL,
	DAMSR_SID_NEW	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, DAMSR_SID_OLD),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DAMSR_SID_OLD) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE,
	FOREIGN KEY (DAMSR_SID_NEW) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_MOVE_DOWN_TO_MEASURE_PARS (
	NAVSS_SID		int NOT NULL,
	DAMSR_SID_OLD	int NOT NULL,
	DAMSR_SID_NEW	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, DAMSR_SID_OLD),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DAMSR_SID_OLD) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE,
	FOREIGN KEY (DAMSR_SID_NEW) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_MOVE_UP_TO_MEASURE_PARS (
	NAVSS_SID		int NOT NULL,
	DAMSR_SID_OLD	int NOT NULL,
	DAMSR_SID_NEW	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, DAMSR_SID_OLD),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DAMSR_SID_OLD) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE,
	FOREIGN KEY (DAMSR_SID_NEW) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_NARROW_AMSR_FILTER_A_PARS (
	NAVSS_SID		int NOT NULL,
	AMSR_PRED_SID	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, AMSR_PRED_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (AMSR_PRED_SID) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_NARROW_AMSR_FILTER_C_PARS (
	NAVSS_SID			int NOT NULL,
	AMSR_PRED_SID_OLD	int NOT NULL,
	AMSR_PRED_SID_NEW	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, AMSR_PRED_SID_OLD),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (AMSR_PRED_SID_OLD) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE,
	FOREIGN KEY (AMSR_PRED_SID_NEW) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_BROADEN_AMSR_FILTER_A_PARS (
	NAVSS_SID		int NOT NULL,
	AMSR_PRED_SID	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, AMSR_PRED_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (AMSR_PRED_SID) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_BROADEN_AMSR_FILTER_C_PARS (
	NAVSS_SID			int NOT NULL,
	AMSR_PRED_SID_OLD	int NOT NULL,
	AMSR_PRED_SID_NEW	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, AMSR_PRED_SID_OLD),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (AMSR_PRED_SID_OLD) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE,
	FOREIGN KEY (AMSR_PRED_SID_NEW) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_REFOCUS_AMSR_FILTER_PARS (
	NAVSS_SID		int NOT NULL,
	AMSR_PRED_SID	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, AMSR_PRED_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (AMSR_PRED_SID) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_REFOCUS_AMSR_FILTER_C_PARS (
	NAVSS_SID			int NOT NULL,
	AMSR_PRED_SID_OLD	int NOT NULL,
	AMSR_PRED_SID_NEW	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, AMSR_PRED_SID_OLD),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (AMSR_PRED_SID_OLD) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE,
	FOREIGN KEY (AMSR_PRED_SID_NEW) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_DRILL_ACROSS_TO_CUBE (
	NAVSS_SID	int NOT NULL PRIMARY KEY,
	CUBE_SID	int NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (CUBE_SID) REFERENCES DW_CUBE(CUBE_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_DRILL_ACROSS_TO_CUBE_BMSR_PRED (
	NAVSS_SID		int NOT NULL,
	BMSR_PRED_SID	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, BMSR_PRED_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_DRILL_ACROSS_TO_CUBE(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (BMSR_PRED_SID) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_DRILL_ACROSS_TO_CUBE_DAMSR (
	NAVSS_SID	int NOT NULL,
	DAMSR_SID	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, DAMSR_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_DRILL_ACROSS_TO_CUBE(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (DAMSR_SID) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_DRILL_ACROSS_TO_CUBE_AMSR_PRED (
	NAVSS_SID		int NOT NULL,
	AMSR_PRED_SID	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, AMSR_PRED_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_DRILL_ACROSS_TO_CUBE(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (AMSR_PRED_SID) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_RELATE (
	NAVSS_SID		int NOT NULL PRIMARY KEY,
	NAVSS_SID_NOP	int,
	NAVSS_OPNAME	varchar(250),
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (NAVSS_SID_NOP) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_RELATE_JOIN (
	NAVSS_JOIN_SID	int NOT NULL PRIMARY KEY,
	NAVSS_SID		int NOT NULL,
	CASS_JOIN_EXPR	varchar(5000) NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_RELATE(NAVSS_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_RELATE_SCORE (
	NAVSS_SID		int NOT NULL,
	SCORE_SID		int NOT NULL,
	
	PRIMARY KEY (NAVSS_SID, SCORE_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_RELATE(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_SID) REFERENCES DW_SCORE(SCORE_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_RELATE_SCORE_FLT (
	NAVSS_SID			int NOT NULL,
	SCORE_PRED_SID		int NOT NULL,
	
	PRIMARY KEY (NAVSS_SID, SCORE_PRED_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_RELATE(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_PRED_SID) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_TARGET (
	NAVSS_SID		int NOT NULL PRIMARY KEY,
	NAVSS_SID_NOP	int,
	NAVSS_OPNAME	varchar(250),
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (NAVSS_SID_NOP) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_TARGET_JOIN (
	NAVSS_JOIN_SID	int NOT NULL PRIMARY KEY,
	NAVSS_SID		int NOT NULL,
	CASS_JOIN_EXPR	varchar(5000) NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_TARGET(NAVSS_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_TARGET_SCORE (
	NAVSS_SID		int NOT NULL,
	SCORE_SID		int NOT NULL,
	
	PRIMARY KEY (NAVSS_SID, SCORE_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_RELATE(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_SID) REFERENCES DW_SCORE(SCORE_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_TARGET_SCORE_FLT (
	NAVSS_SID			int NOT NULL,
	SCORE_PRED_SID		int NOT NULL,
	
	PRIMARY KEY (NAVSS_SID, SCORE_PRED_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_RELATE(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_PRED_SID) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_RERELATE (
	NAVSS_SID		int NOT NULL PRIMARY KEY,
	NAVSS_SID_NOP	int,
	NAVSS_OPNAME	varchar(250),
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (NAVSS_SID_NOP) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_RERELATE_JOIN (
	NAVSS_JOIN_SID	int NOT NULL PRIMARY KEY,
	NAVSS_SID		int NOT NULL,
	CASS_JOIN_EXPR	varchar(5000) NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_RERELATE(NAVSS_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_RERELATE_SCORE (
	NAVSS_SID		int NOT NULL,
	SCORE_SID		int NOT NULL,
	
	PRIMARY KEY (NAVSS_SID, SCORE_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_RELATE(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_SID) REFERENCES DW_SCORE(SCORE_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_RERELATE_SCORE_FLT (
	NAVSS_SID			int NOT NULL,
	SCORE_PRED_SID		int NOT NULL,
	
	PRIMARY KEY (NAVSS_SID, SCORE_PRED_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_RELATE(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_PRED_SID) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_RETARGET (
	NAVSS_SID		int NOT NULL PRIMARY KEY,
	NAVSS_SID_NOP	int,
	NAVSS_OPNAME	varchar(250),
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (NAVSS_SID_NOP) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_RETARGET_JOIN (
	NAVSS_JOIN_SID	int NOT NULL PRIMARY KEY,
	NAVSS_SID		int NOT NULL,
	CASS_JOIN_EXPR	varchar(5000) NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_RETARGET(NAVSS_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_RETARGET_SCORE (
	NAVSS_SID		int NOT NULL,
	SCORE_SID		int NOT NULL,
	
	PRIMARY KEY (NAVSS_SID, SCORE_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_RELATE(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_SID) REFERENCES DW_SCORE(SCORE_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_RETARGET_SCORE_FLT (
	NAVSS_SID			int NOT NULL,
	SCORE_PRED_SID		int NOT NULL,
	
	PRIMARY KEY (NAVSS_SID, SCORE_PRED_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_RELATE(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_PRED_SID) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_CORRELATE (
	NAVSS_SID		int NOT NULL PRIMARY KEY,
	NAVSS_SID_NOP	int,
	NAVSS_OPNAME	varchar(250),
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (NAVSS_SID_NOP) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_CORRELATE_JOIN (
	NAVSS_JOIN_SID	int NOT NULL PRIMARY KEY,
	NAVSS_SID		int NOT NULL,
	CASS_JOIN_EXPR	varchar(5000) NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_CORRELATE(NAVSS_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_CORRELATE_SCORE (
	NAVSS_SID		int NOT NULL,
	SCORE_SID		int NOT NULL,
	
	PRIMARY KEY (NAVSS_SID, SCORE_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_RELATE(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_SID) REFERENCES DW_SCORE(SCORE_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_CORRELATE_SCORE_FLT (
	NAVSS_SID			int NOT NULL,
	SCORE_PRED_SID		int NOT NULL,
	
	PRIMARY KEY (NAVSS_SID, SCORE_PRED_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSS_RELATE(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_PRED_SID) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_NARROW_SCORE_FILTER_A_PARS (
	NAVSS_SID		int NOT NULL,
	SCORE_PRED_SID	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, SCORE_PRED_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_PRED_SID) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_NARROW_SCORE_FILTER_C_PARS (
	NAVSS_SID			int NOT NULL,
	SCORE_PRED_SID_OLD	int NOT NULL,
	SCORE_PRED_SID_NEW	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, SCORE_PRED_SID_OLD),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_PRED_SID_OLD) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_PRED_SID_NEW) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_BROADEN_SCORE_FILTER_A_PARS (
	NAVSS_SID		int NOT NULL,
	SCORE_PRED_SID	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, SCORE_PRED_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_PRED_SID) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_BROADEN_SCORE_FILTER_C_PARS (
	NAVSS_SID			int NOT NULL,
	SCORE_PRED_SID_OLD	int NOT NULL,
	SCORE_PRED_SID_NEW	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, SCORE_PRED_SID_OLD),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_PRED_SID_OLD) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_PRED_SID_NEW) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_REFOCUS_SCORE_FILTER_PARS (
	NAVSS_SID		int NOT NULL,
	SCORE_PRED_SID	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, SCORE_PRED_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_PRED_SID) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_REFOCUS_SCORE_FILTER_C_PARS (
	NAVSS_SID			int NOT NULL,
	SCORE_PRED_SID_OLD	int NOT NULL,
	SCORE_PRED_SID_NEW	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, SCORE_PRED_SID_OLD),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_PRED_SID_OLD) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_PRED_SID_NEW) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_REJOIN_JOIN (
	NAVSS_JOIN_SID	int NOT NULL PRIMARY KEY,
	NAVSS_SID		int NOT NULL,
	CASS_JOIN_EXPR	varchar(5000) NOT NULL,
	
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_REJOIN_SCORE (
	NAVSS_SID	int NOT NULL,
	SCORE_SID	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, SCORE_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_SID) REFERENCES DW_SCORE(SCORE_SID) ON DELETE CASCADE
);

CREATE TABLE AGS_NAVSS_REJOIN_SCORE_FLT (
	NAVSS_SID		int NOT NULL,
	SCORE_PRED_SID	int NOT NULL,

	PRIMARY KEY (NAVSS_SID, SCORE_PRED_SID),
	FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
	FOREIGN KEY (SCORE_PRED_SID) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_ANALYSIS_GRAPH (
 AG_SID int NOT NULL PRIMARY KEY,
 AGS_SID int NOT NULL,
 AG_NAME varchar(250) NOT NULL UNIQUE,
 AG_DESCRIPTION varchar(5000),
	
 FOREIGN KEY (AGS_SID) REFERENCES AGS_ANALYSIS_GRAPH_SCHEMA(AGS_SID) ON DELETE CASCADE
);

CREATE TABLE AG_ANALYSIS_SITUATION (
 AS_SID int NOT NULL PRIMARY KEY,
 ASS_SID int NOT NULL,
 AS_NAME varchar(250) NOT NULL,
 AS_DESCRIPTION varchar(5000),
 AG_SID int NOT NULL,
 AS_POS_X int NOT NULL,
 AS_POS_Y int NOT NULL,
	
 FOREIGN KEY (ASS_SID) REFERENCES AGS_ANALYSIS_SITUATION_SCHEMA(ASS_SID) ON DELETE CASCADE,
 FOREIGN KEY (AG_SID) REFERENCES AG_ANALYSIS_GRAPH(AG_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NON_CMP_AS (
 AS_SID_NAS int NOT NULL PRIMARY KEY,
 AS_USED_IN_CAS smallint NOT NULL,	
 CUBE_SID int NOT NULL,
 
 FOREIGN KEY (AS_SID_NAS) REFERENCES AG_ANALYSIS_SITUATION(AS_SID) ON DELETE CASCADE,
 FOREIGN KEY (CUBE_SID) REFERENCES DW_CUBE(CUBE_SID) ON DELETE CASCADE
);

CREATE TABLE AG_CMP_AS (
 AS_SID_CAS int NOT NULL PRIMARY KEY,
 AS_SID_NAS_COI int NOT NULL,
 AS_SID_NAS_COC int NOT NULL,
 	
 FOREIGN KEY (AS_SID_CAS) REFERENCES AG_ANALYSIS_SITUATION(AS_SID) ON DELETE CASCADE,	
 FOREIGN KEY (AS_SID_NAS_COI) REFERENCES AG_NON_CMP_AS(AS_SID_NAS) ON DELETE CASCADE,
 FOREIGN KEY (AS_SID_NAS_COC) REFERENCES AG_NON_CMP_AS(AS_SID_NAS) ON DELETE CASCADE
);

CREATE TABLE AG_COMPOSITE_AS (
 AS_SID_COMPOSITE int NOT NULL PRIMARY KEY,
 AS_SID_ROOT int NOT NULL,
 	
 FOREIGN KEY (AS_SID_COMPOSITE) REFERENCES AG_ANALYSIS_SITUATION(AS_SID) ON DELETE CASCADE,
 FOREIGN KEY (AS_SID_ROOT) REFERENCES AG_ANALYSIS_SITUATION(AS_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAS_DIM_QUAL (
 NAS_DQ_SID int NOT NULL PRIMARY KEY,
 AS_SID_NAS int NOT NULL,
 DIM_SID int NOT NULL,
 LVL_SID_DICELVL int NOT NULL,
 NAS_DQ_DICE_NODE varchar(5000) NOT NULL,
 LVL_SID_GRANLVL int NOT NULL,
 	
 FOREIGN KEY (AS_SID_NAS) REFERENCES AG_NON_CMP_AS(AS_SID_NAS) ON DELETE CASCADE,
 FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE,
 FOREIGN KEY (LVL_SID_DICELVL) REFERENCES DW_LEVEL(LVL_SID) ON DELETE CASCADE,
 FOREIGN KEY (LVL_SID_GRANLVL) REFERENCES DW_LEVEL(LVL_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAS_DIM_QUAL_SLICE_COND (
 NAS_SC_SID int NOT NULL PRIMARY KEY,
 NAS_DQ_SID int NOT NULL,
 DIM_PRED_SID int NOT NULL,	
 
 FOREIGN KEY (NAS_DQ_SID) REFERENCES AG_NAS_DIM_QUAL(NAS_DQ_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_PRED_SID) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAS_BMSR_FILTER (
 NAS_BMSR_FLT_SID int NOT NULL PRIMARY KEY,
 AS_SID_NAS int NOT NULL,
 BMSR_PRED_SID int NOT NULL,
 
 FOREIGN KEY (AS_SID_NAS) REFERENCES AG_NON_CMP_AS(AS_SID_NAS) ON DELETE CASCADE,
 FOREIGN KEY (BMSR_PRED_SID) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAS_AGGREGATE_MEASURE (
 NAS_AMSR_SID int NOT NULL PRIMARY KEY,
 AS_SID_NAS int NOT NULL,
 DAMSR_SID int NOT NULL,
 
 FOREIGN KEY (AS_SID_NAS) REFERENCES AG_NON_CMP_AS(AS_SID_NAS) ON DELETE CASCADE,
 FOREIGN KEY (DAMSR_SID) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAS_AMSR_FILTER (
 NAS_AMSR_FLT_SID int NOT NULL PRIMARY KEY,
 AS_SID_NAS int NOT NULL,
 AMSR_PRED_SID int NOT NULL,
 
 FOREIGN KEY (AS_SID_NAS) REFERENCES AG_NON_CMP_AS(AS_SID_NAS) ON DELETE CASCADE,
 FOREIGN KEY (AMSR_PRED_SID) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_CAS_JOIN_COND (
 CAS_JOIN_SID int NOT NULL PRIMARY KEY,
 AS_SID_CAS int NOT NULL,
 CAS_JOIN_EXPR varchar(5000) NOT NULL,
 
 FOREIGN KEY (AS_SID_CAS) REFERENCES AG_CMP_AS(AS_SID_CAS) ON DELETE CASCADE
);

CREATE TABLE AG_CAS_SCORE (
 CAS_SCORE_SID int NOT NULL PRIMARY KEY,
 AS_SID_CAS int NOT NULL,
 SCORE_SID int NOT NULL,
 
 FOREIGN KEY (AS_SID_CAS) REFERENCES AG_CMP_AS(AS_SID_CAS) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_SID) REFERENCES DW_SCORE(SCORE_SID) ON DELETE CASCADE
);

CREATE TABLE AG_CAS_SCORE_FILTER (
 CAS_SCORE_FLT_SID int NOT NULL PRIMARY KEY,
 AS_SID_CAS int NOT NULL,
 SCORE_PRED_SID int NOT NULL,
 
 FOREIGN KEY (AS_SID_CAS) REFERENCES AG_CMP_AS(AS_SID_CAS) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_PRED_SID) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_COMPOSITE_AS_PART (
 AS_SID_COMPOSITE int NOT NULL,
 AS_SID_PART int NOT NULL,
 
 PRIMARY KEY (AS_SID_COMPOSITE, AS_SID_PART),
 FOREIGN KEY (AS_SID_COMPOSITE) REFERENCES AG_COMPOSITE_AS(AS_SID_COMPOSITE) ON DELETE CASCADE,
 FOREIGN KEY (AS_SID_PART) REFERENCES AG_ANALYSIS_SITUATION(AS_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVSTEP (
 NAVS_SID int NOT NULL PRIMARY KEY,
 NAVSS_SID int NOT NULL,
 AG_SID int NOT NULL,
 AS_SID_SOURCE int NOT NULL,
 AS_SID_TARGET int NOT NULL,
 NAVS_OPNAME varchar(250) NOT NULL,
 NAVS_GRD_EXPR varchar(5000),
 NAVS_USED_IN_CMPNAV smallint NOT NULL,
 NAVS_POS_X int NOT NULL,
 NAVS_POS_Y int NOT NULL,
 NAVS_POS_GRD_X int NOT NULL,
 NAVS_POS_GRD_Y int NOT NULL,
 
 FOREIGN KEY (NAVSS_SID) REFERENCES AGS_NAVSTEP_SCHEMA(NAVSS_SID) ON DELETE CASCADE,
 FOREIGN KEY (AG_SID) REFERENCES AG_ANALYSIS_GRAPH(AG_SID) ON DELETE CASCADE,
 FOREIGN KEY (AS_SID_SOURCE) REFERENCES AG_ANALYSIS_SITUATION(AS_SID) ON DELETE CASCADE,
 FOREIGN KEY (AS_SID_TARGET) REFERENCES AG_ANALYSIS_SITUATION(AS_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_DRILL_DOWN_ONE_LEVEL (
 NAVS_SID int NOT NULL PRIMARY KEY,
 DIM_SID int NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_DRILL_DOWN_TO_LEVEL (
 NAVS_SID int NOT NULL PRIMARY KEY,
 DIM_SID int NOT NULL,
 LVL_SID_GRANLVL int,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE,
 FOREIGN KEY (LVL_SID_GRANLVL) REFERENCES DW_LEVEL(LVL_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_ROLL_UP_ONE_LEVEL (
 NAVS_SID int NOT NULL PRIMARY KEY,
 DIM_SID int NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_ROLL_UP_TO_LEVEL (
 NAVS_SID int NOT NULL PRIMARY KEY,
 DIM_SID int NOT NULL,
 LVL_SID_GRANLVL int,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE,
 FOREIGN KEY (LVL_SID_GRANLVL) REFERENCES DW_LEVEL(LVL_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_MOVE_DOWN_TO_NODE (
 NAVS_SID int NOT NULL PRIMARY KEY,
 DIM_SID int NOT NULL,
 LVL_SID_DICELVL int NOT NULL,
 NAVS_DICE_NODE varchar(5000) NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE,
 FOREIGN KEY (LVL_SID_DICELVL) REFERENCES DW_LEVEL(LVL_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_MOVE_UP_TO_NODE (
 NAVS_SID int NOT NULL PRIMARY KEY,
 DIM_SID int NOT NULL,
 LVL_SID_DICELVL int NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE,
 FOREIGN KEY (LVL_SID_DICELVL) REFERENCES DW_LEVEL(LVL_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_MOVE_ASIDE_TO_NODE (
 NAVS_SID int NOT NULL PRIMARY KEY,
 DIM_SID int NOT NULL,
 NAVS_DICE_NODE varchar(5000) NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_MOVE_TO_NODE (
 NAVS_SID int NOT NULL PRIMARY KEY,
 DIM_SID int NOT NULL,
 LVL_SID_DICELVL int NOT NULL,
 NAVS_DICE_NODE varchar(5000) NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE,
 FOREIGN KEY (LVL_SID_DICELVL) REFERENCES DW_LEVEL(LVL_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_MOVE_TO_FIRST_NODE (
 NAVS_SID int NOT NULL PRIMARY KEY,
 DIM_SID int NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_MOVE_TO_LAST_NODE (
 NAVS_SID int NOT NULL PRIMARY KEY,
 DIM_SID int NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_MOVE_TO_NEXT_NODE (
 NAVS_SID int NOT NULL PRIMARY KEY,
 DIM_SID int NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_MOVE_TO_PREV_NODE (
 NAVS_SID int NOT NULL PRIMARY KEY,
 DIM_SID int NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_NARROW_SLICE_COND_A (
 NAVS_SID int NOT NULL PRIMARY KEY,
 DIM_SID int NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_NARROW_SLICE_COND_A_PARS (
 NAVS_SID int NOT NULL,
 DIM_PRED_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, DIM_PRED_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_PRED_SID) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_NARROW_SLICE_COND_C (
 NAVS_SID int NOT NULL PRIMARY KEY,
 DIM_SID int NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_NARROW_SLICE_COND_C_PARS (
 NAVS_SID int NOT NULL,
 DIM_PRED_SID_OLD int NOT NULL,
 DIM_PRED_SID_NEW int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, DIM_PRED_SID_OLD),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_PRED_SID_OLD) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_PRED_SID_NEW) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_BROADEN_SLICE_COND_A (
 NAVS_SID int NOT NULL PRIMARY KEY,
 DIM_SID int NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_BROADEN_SLICE_COND_A_PARS (
 NAVS_SID int NOT NULL,
 DIM_PRED_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, DIM_PRED_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_PRED_SID) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_BROADEN_SLICE_COND_C (
 NAVS_SID int NOT NULL PRIMARY KEY,
 DIM_SID int NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_BROADEN_SLICE_COND_C_PARS (
 NAVS_SID int NOT NULL,
 DIM_PRED_SID_OLD int NOT NULL,
 DIM_PRED_SID_NEW int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, DIM_PRED_SID_OLD),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_PRED_SID_OLD) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_PRED_SID_NEW) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_REFOCUS_SLICE_COND (
 NAVS_SID int NOT NULL PRIMARY KEY,
 DIM_SID int NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_REFOCUS_SLICE_COND_PARS (
 NAVS_SID int NOT NULL,
 DIM_PRED_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, DIM_PRED_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_PRED_SID) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_REFOCUS_SLICE_COND_C (
 NAVS_SID int NOT NULL PRIMARY KEY,
 DIM_SID int NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_SID) REFERENCES DW_DIMENSION(DIM_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_REFOCUS_SLICE_COND_C_PARS (
 NAVS_SID int NOT NULL,
 DIM_PRED_SID_OLD int NOT NULL,
 DIM_PRED_SID_NEW int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, DIM_PRED_SID_OLD),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_PRED_SID_OLD) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE,
 FOREIGN KEY (DIM_PRED_SID_NEW) REFERENCES DW_DIM_PREDICATE(DIM_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_NARROW_BMSR_COND_A_PARS (
 NAVS_SID int NOT NULL,
 BMSR_PRED_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, BMSR_PRED_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (BMSR_PRED_SID) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_NARROW_BMSR_COND_C_PARS (
 NAVS_SID int NOT NULL,
 BMSR_PRED_SID_OLD int NOT NULL,
 BMSR_PRED_SID_NEW int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, BMSR_PRED_SID_OLD),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (BMSR_PRED_SID_OLD) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE,
 FOREIGN KEY (BMSR_PRED_SID_NEW) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_BROADEN_BMSR_COND_A_PARS (
 NAVS_SID int NOT NULL,
 BMSR_PRED_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, BMSR_PRED_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (BMSR_PRED_SID) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_BROADEN_BMSR_COND_C_PARS (
 NAVS_SID int NOT NULL,
 BMSR_PRED_SID_OLD int NOT NULL,
 BMSR_PRED_SID_NEW int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, BMSR_PRED_SID_OLD),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (BMSR_PRED_SID_OLD) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE,
 FOREIGN KEY (BMSR_PRED_SID_NEW) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_REFOCUS_BMSR_COND_PARS (
 NAVS_SID int NOT NULL,
 BMSR_PRED_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, BMSR_PRED_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (BMSR_PRED_SID) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_REFOCUS_BMSR_COND_C_PARS (
 NAVS_SID int NOT NULL,
 BMSR_PRED_SID_OLD int NOT NULL,
 BMSR_PRED_SID_NEW int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, BMSR_PRED_SID_OLD),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (BMSR_PRED_SID_OLD) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE,
 FOREIGN KEY (BMSR_PRED_SID_NEW) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_ADD_MEASURE_PARS (
 NAVS_SID int NOT NULL,
 DAMSR_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, DAMSR_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DAMSR_SID) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_DROP_MEASURE_PARS (
 NAVS_SID int NOT NULL,
 DAMSR_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, DAMSR_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DAMSR_SID) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_REFOCUS_MEASURE_PARS (
 NAVS_SID int NOT NULL,
 DAMSR_SID int NOT NULL,
  
 PRIMARY KEY (NAVS_SID, DAMSR_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DAMSR_SID) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_REFOCUS_MEASURE_C_PARS (
 NAVS_SID int NOT NULL,
 DAMSR_SID_OLD int NOT NULL,
 DAMSR_SID_NEW int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, DAMSR_SID_OLD),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DAMSR_SID_OLD) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE,
 FOREIGN KEY (DAMSR_SID_NEW) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_MOVE_DOWN_TO_MEASURE_PARS (
 NAVS_SID int NOT NULL,
 DAMSR_SID_OLD int NOT NULL,
 DAMSR_SID_NEW int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, DAMSR_SID_OLD),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DAMSR_SID_OLD) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE,
 FOREIGN KEY (DAMSR_SID_NEW) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_MOVE_UP_TO_MEASURE_PARS (
 NAVS_SID int NOT NULL,
 DAMSR_SID_OLD int NOT NULL,
 DAMSR_SID_NEW int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, DAMSR_SID_OLD),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DAMSR_SID_OLD) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE,
 FOREIGN KEY (DAMSR_SID_NEW) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_NARROW_AMSR_FILTER_A_PARS (
 NAVS_SID int NOT NULL,
 AMSR_PRED_SID int NOT NULL,
  
 PRIMARY KEY (NAVS_SID, AMSR_PRED_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (AMSR_PRED_SID) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_NARROW_AMSR_FILTER_C_PARS (
 NAVS_SID int NOT NULL,
 AMSR_PRED_SID_OLD int NOT NULL,
 AMSR_PRED_SID_NEW int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, AMSR_PRED_SID_OLD),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (AMSR_PRED_SID_OLD) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE,
 FOREIGN KEY (AMSR_PRED_SID_NEW) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_BROADEN_AMSR_FILTER_A_PARS (
 NAVS_SID int NOT NULL,
 AMSR_PRED_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, AMSR_PRED_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (AMSR_PRED_SID) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_BROADEN_AMSR_FILTER_C_PARS (
 NAVS_SID int NOT NULL,
 AMSR_PRED_SID_OLD int NOT NULL,
 AMSR_PRED_SID_NEW int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, AMSR_PRED_SID_OLD),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (AMSR_PRED_SID_OLD) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE,
 FOREIGN KEY (AMSR_PRED_SID_NEW) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_REFOCUS_AMSR_FILTER_PARS (
 NAVS_SID int NOT NULL,
 AMSR_PRED_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, AMSR_PRED_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (AMSR_PRED_SID) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_REFOCUS_AMSR_FILTER_C_PARS (
 NAVS_SID int NOT NULL,
 AMSR_PRED_SID_OLD int NOT NULL,
 AMSR_PRED_SID_NEW int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, AMSR_PRED_SID_OLD),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (AMSR_PRED_SID_OLD) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE,
 FOREIGN KEY (AMSR_PRED_SID_NEW) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_DRILL_ACROSS_TO_CUBE (
 NAVS_SID int NOT NULL PRIMARY KEY,
 CUBE_SID int NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (CUBE_SID) REFERENCES DW_CUBE(CUBE_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_DRILL_ACROSS_TO_CUBE_BMSR_PRED (
 NAVS_SID int NOT NULL,
 BMSR_PRED_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, BMSR_PRED_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (BMSR_PRED_SID) REFERENCES DW_BMSR_PREDICATE(BMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_DRILL_ACROSS_TO_CUBE_DAMSR (
 NAVS_SID int NOT NULL,
 DAMSR_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, DAMSR_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (DAMSR_SID) REFERENCES DW_DERIVED_AGGREGATE_MEASURE(DAMSR_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_DRILL_ACROSS_TO_CUBE_AMSR_PRED (
 NAVS_SID int NOT NULL,
 AMSR_PRED_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, AMSR_PRED_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (AMSR_PRED_SID) REFERENCES DW_AMSR_PREDICATE(AMSR_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_RELATE (
 NAVS_SID int NOT NULL PRIMARY KEY,
 NAVS_SID_NOP int,
 NAVS_OPNAME varchar(250),
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (NAVS_SID_NOP) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_RELATE_JOIN (
 NAVS_JOIN_SID int NOT NULL PRIMARY KEY,
 NAVS_SID int NOT NULL,
 CAS_JOIN_EXPR varchar(5000) NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_RELATE_SCORE (
 NAVS_SID int NOT NULL,
 SCORE_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, SCORE_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_SID) REFERENCES DW_SCORE(SCORE_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_RELATE_SCORE_FLT (
 NAVS_SID int NOT NULL,
 SCORE_PRED_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, SCORE_PRED_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_PRED_SID) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_TARGET (
 NAVS_SID int NOT NULL PRIMARY KEY,
 NAVS_SID_NOP int,
 NAVS_OPNAME varchar(250),
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (NAVS_SID_NOP) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_TARGET_JOIN (
 NAVS_JOIN_SID int NOT NULL PRIMARY KEY,
 NAVS_SID int NOT NULL,
 CAS_JOIN_EXPR varchar(5000) NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_TARGET_SCORE (
 NAVS_SID int NOT NULL,
 SCORE_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, SCORE_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_SID) REFERENCES DW_SCORE(SCORE_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_TARGET_SCORE_FLT (
 NAVS_SID int NOT NULL,
 SCORE_PRED_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, SCORE_PRED_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_PRED_SID) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_RERELATE (
 NAVS_SID int NOT NULL PRIMARY KEY,
 NAVS_SID_NOP int,
 NAVS_OPNAME varchar(250),
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (NAVS_SID_NOP) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_RERELATE_JOIN (
 NAVS_JOIN_SID int NOT NULL PRIMARY KEY,
 NAVS_SID int NOT NULL,
 CAS_JOIN_EXPR varchar(5000) NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_RERELATE_SCORE (
 NAVS_SID int NOT NULL,
 SCORE_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, SCORE_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_SID) REFERENCES DW_SCORE(SCORE_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_RERELATE_SCORE_FLT (
 NAVS_SID int NOT NULL,
 SCORE_PRED_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, SCORE_PRED_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_PRED_SID) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_RETARGET (
 NAVS_SID int NOT NULL PRIMARY KEY,
 NAVS_SID_NOP int,
 NAVS_OPNAME varchar(250),
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (NAVS_SID_NOP) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_RETARGET_JOIN (
 NAVS_JOIN_SID int NOT NULL PRIMARY KEY,
 NAVS_SID int NOT NULL,
 CAS_JOIN_EXPR varchar(5000) NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_RETARGET_SCORE (
 NAVS_SID int NOT NULL,
 SCORE_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, SCORE_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_SID) REFERENCES DW_SCORE(SCORE_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_RETARGET_SCORE_FLT (
 NAVS_SID int NOT NULL,
 SCORE_PRED_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, SCORE_PRED_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_PRED_SID) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_CORRELATE (
 NAVS_SID int NOT NULL PRIMARY KEY,
 NAVS_SID_NOP int,
 NAVS_OPNAME varchar(250),
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (NAVS_SID_NOP) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_CORRELATE_JOIN (
 NAVS_JOIN_SID int NOT NULL PRIMARY KEY,
 NAVS_SID int NOT NULL,
 CAS_JOIN_EXPR varchar(5000) NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_CORRELATE_SCORE (
 NAVS_SID int NOT NULL,
 SCORE_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, SCORE_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_SID) REFERENCES DW_SCORE(SCORE_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_CORRELATE_SCORE_FLT (
 NAVS_SID int NOT NULL,
 SCORE_PRED_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, SCORE_PRED_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_PRED_SID) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_NARROW_SCORE_FILTER_A_PARS (
 NAVS_SID int NOT NULL,
 SCORE_PRED_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, SCORE_PRED_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_PRED_SID) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_NARROW_SCORE_FILTER_C_PARS (
 NAVS_SID int NOT NULL,
 SCORE_PRED_SID_OLD int NOT NULL,
 SCORE_PRED_SID_NEW int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, SCORE_PRED_SID_OLD),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_PRED_SID_OLD) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_PRED_SID_NEW) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_BROADEN_SCORE_FILTER_A_PARS (
 NAVS_SID int NOT NULL,
 SCORE_PRED_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, SCORE_PRED_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_PRED_SID) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_BROADEN_SCORE_FILTER_C_PARS (
 NAVS_SID int NOT NULL,
 SCORE_PRED_SID_OLD int NOT NULL,
 SCORE_PRED_SID_NEW int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, SCORE_PRED_SID_OLD),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_PRED_SID_OLD) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_PRED_SID_NEW) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_REFOCUS_SCORE_FILTER_PARS (
 NAVS_SID int NOT NULL,
 SCORE_PRED_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, SCORE_PRED_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_PRED_SID) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_REFOCUS_SCORE_FILTER_C_PARS (
 NAVS_SID int NOT NULL,
 SCORE_PRED_SID_OLD int NOT NULL,
 SCORE_PRED_SID_NEW int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, SCORE_PRED_SID_OLD),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_PRED_SID_OLD) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_PRED_SID_NEW) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_REJOIN_JOIN (
 NAVS_JOIN_SID int NOT NULL PRIMARY KEY,
 NAVS_SID int NOT NULL,
 CAS_JOIN_EXPR varchar(5000) NOT NULL,
 
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_REJOIN_SCORE (
 NAVS_SID int NOT NULL,
 SCORE_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, SCORE_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_SID) REFERENCES DW_SCORE(SCORE_SID) ON DELETE CASCADE
);

CREATE TABLE AG_NAVS_REJOIN_SCORE_FLT (
 NAVS_SID int NOT NULL,
 SCORE_PRED_SID int NOT NULL,
 
 PRIMARY KEY (NAVS_SID, SCORE_PRED_SID),
 FOREIGN KEY (NAVS_SID) REFERENCES AG_NAVSTEP(NAVS_SID) ON DELETE CASCADE,
 FOREIGN KEY (SCORE_PRED_SID) REFERENCES DW_SCORE_PREDICATE(SCORE_PRED_SID) ON DELETE CASCADE
);

	